version: '2'

# Base Compose File for the Cyclone Federation Provider

services:
  samlbridge:
    build: ./components/samlbridge
    restart: unless-stopped
    environment:
      - FP_BASEURL
      - SAMLBRIDGE_CRON
      - SAMLBRIDGE_PASSWORD
      - SAMLBRIDGE_SALT
      - SAMLBRIDGE_CONTACTNAME
      - SAMLBRIDGE_CONTACTEMAIL
    volumes:
      - ./components/samlbridge/samlbridge-cert:/var/simplesamlphp/cert
      - ./components/samlbridge/samlbridge-config:/var/simplesamlphp/config
      - ./components/samlbridge/modules/cyclone:/var/simplesamlphp/modules/cyclone
      - ./components/samlbridge/saml20-sp-remote.php:/var/simplesamlphp/metadata/saml20-sp-remote.php
      - ./components/samlbridge/saml20-idp-hosted.php:/var/simplesamlphp/metadata/saml20-idp-hosted.php
      - ./components/samlbridge/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./components/samlbridge/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./components/samlbridge/mpm_prefork.conf:/etc/apache2/mods-enabled/mpm_prefork.conf
    expose:
      - "80"
    ports:
      - "80:80"
