defaultEntryPoints = ["http", "https"]
    [entryPoints]
        [entryPoints.http]
        address = ":80"
            [entryPoints.http.redirect]
                entryPoint = "https"
        [entryPoints.https]
        address = ":443"
            [entryPoints.https.tls]

[acme]
email = "support@sixsq.com"
storage = "acme.json"
entryPoint = "https"
[[acme.domains]]
   main = "fed-id.nuv.la"
